version: "3.9"

services:

  flask_app:
    container_name: flask_app
    image: flask_app_image
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    networks:
      - my-net
       
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-net

volumes:
  pgdata: {}

networks:
  my-net:
    driver: bridge