version: "3.9"

services:

  flask_app:
    container_name: flask_app
    image: flask_app_image
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    networks:
      - my-net
       
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-net

  nginx:
    image: nginx:1.25.4-alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .app.py:/usr/share/nginx/html
    ports:
      - "80:80"  # Mapping container port 80 to host port 8000 to avoid confusion from local nginx
    
    depends_on:
      - flask_app  
      - flask_db
    networks:
     - my-net  

volumes:
  pgdata: {}

networks:
  my-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16